### ISSUE TITLE
ECONNRESET error in Azure Continuous WebJob

### ISSUE THREAD

**Issue by dmoreno** [Azure/azure-documentdb-node#137]
Hi everyone!

I am writing a continuous WebJob in Azure WebApp with DocumentDB access. But I get an ECONNRESET error 2 minutes after starting webjob, aborting webjob execution and forcing webjob restart. This happens in every run. This is a minimal example for this reproducible behavior.

```js
const DocumentClient = require('documentdb').DocumentClient;
var documentClient = new DocumentClient("https://[COLLECTION_NAME].documents.azure.com:443/", {masterKey: [MASTER_KEY]});

documentClient.readDatabases().toArray((err, databases) => {
    if(err) return;
    console.log(databases);
});
        
runContinuousJobWithTimeouts();

function runContinuousJobWithTimeouts() {
    console.log("runContinuousJobWithTimeouts");
    setTimeout(runContinuousJobWithTimeouts, 10000);
}
```

WebJob output is:

```
[08/24/2016 10:55:55 > 00c0b0: SYS INFO] Status changed to Running
[08/24/2016 10:55:56 > 00c0b0: INFO] [ { id: '...',
[08/24/2016 10:55:56 > 00c0b0: INFO]     _rid: '...',
[08/24/2016 10:55:56 > 00c0b0: INFO]     _self: '...',
[08/24/2016 10:55:56 > 00c0b0: INFO]     _etag: '"..."',
[08/24/2016 10:55:56 > 00c0b0: INFO]     _ts: ...,
[08/24/2016 10:55:56 > 00c0b0: INFO]     _colls: '...',
[08/24/2016 10:55:56 > 00c0b0: INFO]     _users: '...' } ]
[08/24/2016 10:55:56 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:56:06 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:56:16 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:56:26 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:56:36 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:56:46 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:56:56 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:57:06 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:57:16 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:57:26 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:57:36 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:57:46 > 00c0b0: INFO] runContinuousJob
[08/24/2016 10:57:54 > 00c0b0: ERR ] events.js:141
[08/24/2016 10:57:54 > 00c0b0: ERR ]       throw er; // Unhandled 'error' event
[08/24/2016 10:57:54 > 00c0b0: ERR ]       ^
[08/24/2016 10:57:54 > 00c0b0: ERR ] 
[08/24/2016 10:57:54 > 00c0b0: ERR ] Error: read ECONNRESET
[08/24/2016 10:57:54 > 00c0b0: ERR ]     at exports._errnoException (util.js:874:11)
[08/24/2016 10:57:54 > 00c0b0: ERR ]     at TLSWrap.onread (net.js:544:26)
[08/24/2016 10:57:54 > 00c0b0: SYS ERR ] Job failed due to exit code 1
[08/24/2016 10:57:54 > 00c0b0: SYS INFO] Process went down, waiting for 60 seconds
[08/24/2016 10:57:54 > 00c0b0: SYS INFO] Status changed to PendingRestart
```

Azure WebApp is offering node 4.2.3 in its cloud runtime environment.

Could this be a bug?

**Comment by dmoreno** [comment]
This issue is related to #102.

You can fix the issue forcing a newer version of NodeJS in Azure WebApp. This is configurable with WEBSITE_NODE_DEFAULT_VERSION variable environment in application settings.

Fixed with:
WEBSITE_NODE_DEFAULT_VERSION: 4.4.7
