### ISSUE TITLE
Request path contains unescaped characters.

### ISSUE THREAD

**Issue by ulrikaugustsson** [Azure/azure-documentdb-node#59]
I'm getting this error when trying to query for my collection.
```
_http_client.js:50
    throw new TypeError('Request path contains unescaped characters.');
          ^
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:50:11)
    at Object.exports.request (http.js:30:10)
    at Object.exports.request (https.js:115:15)
    at createRequestObject (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/request.js:36:30)
    at Object.RequestHandler.request (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/request.js:131:32)
    at DocumentClient.Base.defineClass.post (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/documentclient.js:1481:35)
    at DocumentClient.Base.defineClass.queryFeed (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/documentclient.js:1545:32)
    at null.fetchFunction (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/documentclient.js:697:32)
    at Base.defineClass._fetchMore (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/queryIterator.js:192:18)
    at Base.defineClass._toArrayImplementation (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/queryIterator.js:149:22)
    at Base.defineClass.toArray (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/queryIterator.js:114:18)
    at getOrCreateCollection (/home/ulrik/projects/stridhmedia/dist/server/modules/article/index.js:125:79)
    at /home/ulrik/projects/stridhmedia/dist/server/modules/article/index.js:25:9
    at /home/ulrik/projects/stridhmedia/dist/server/modules/article/index.js:111:28
    at Base.defineClass._toArrayImplementation (/home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/queryIterator.js:159:17)
    at /home/ulrik/projects/stridhmedia/node_modules/documentdb/lib/queryIterator.js:155:26
```
The code that generates the error is pretty much taken from the guide at https://azure.microsoft.com/sv-se/documentation/articles/documentdb-nodejs-application/

```js
	function getOrCreateCollection(databaseLink, collectionId, callback) {
		var querySpec = {
			query: "SELECT * FROM root r WHERE r.id='articles'"
		};
		
		client.queryCollections(databaseLink, querySpec).toArray(function (err, results) {
			if (err) {
				callback(err);
			} else {        
				if (results.length === 0) {
					var collectionSpec = {
						id: collectionId
					};
			
					client.createCollection(databaseLink, collectionSpec, function (err, created) {
						callback(null, created);
					});
			
				} else {
					callback(null, results[0]);
				}
			}
		});
	}
```
specifically it's this line:
`client.queryCollections(databaseLink, querySpec).toArray(function (err, results) {`
Am I doing something wrong or is this a bug?

**Comment by ulrikaugustsson** [comment]
I obviously need to use `database._self` when calling the function. Sorry about this issue.
