### ISSUE TITLE
`Hash` directory should be renamed to `hash`

### ISSUE THREAD

**Issue by kenhowardpdx** [Azure/azure-documentdb-node#90]
I'm getting the following error when running my tests on TravisCI.

```
Error: Cannot find module './hash/hashPartitionResolver'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/travis/build/kenhowardpdx/documentdb-orm/node_modules/documentdb/lib/index.js:27:12)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/travis/build/kenhowardpdx/documentdb-orm/node_modules/documentdb/index.js:24:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/travis/build/kenhowardpdx/documentdb-orm/lib/index.js:2:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/travis/build/kenhowardpdx/documentdb-orm/index.js:4:13)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/travis/build/kenhowardpdx/documentdb-orm/test/utils.js:4:13)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/travis/build/kenhowardpdx/documentdb-orm/test/connection.test.js:1:15)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at /home/travis/build/kenhowardpdx/documentdb-orm/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/kenhowardpdx/documentdb-orm/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/home/travis/build/kenhowardpdx/documentdb-orm/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/home/travis/build/kenhowardpdx/documentdb-orm/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

Here's a link to a failing build: https://travis-ci.org/cannonjs/cannon/builds/99786337

**Comment by JanneSalo** [comment]
Please merge this pull request and create a new release ASAP. And please run your tests on an case-sensitive file system so that nothing like this happens again. In my opinion it's unacceptable for a module to break down like this, especially when it breaks dependant modules too (see <https://github.com/Azure/azure-documentdb-node-q/issues/5>).

**Comment by kenhowardpdx** [comment]
I agree that there should be a test suite. I'd be happy to write a test for this PR.

**Comment by ryancrawcour** [comment]
As a rule, there should be a test for each PR submitted.

**Comment by kenhowardpdx** [comment]
Yeah. I just looked again and saw the test folder. Sorry. I'll add one :)

**Comment by kenhowardpdx** [comment]
Meh. Maybe not. I didn't do any code change, just fixed a directory path. Although, I do think this project should have automated tests using something like AppVeyor, TravisCI, or Codeship.

BTW `mocha -t 0 -R spec` fails without any changes on my machine. Running the individual test files works except for `mocha test.js`.
