### ISSUE TITLE
Can't run test suite

### ISSUE THREAD

**Issue by joaomoreno** [Azure/azure-documentdb-node#97]
I followed the instructions in [source/test/readme.md](https://github.com/Azure/azure-documentdb-node/blob/master/source/test/readme.md) but only get this:

```
→ mocha -t 0 -R spec
module.js:327
    throw err;
    ^

Error: Cannot find module 'documentdb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/joao/Work/azure-documentdb-node/source/test/test.js:26:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/joao/.nvm/versions/node/v5.4.1/lib/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/joao/.nvm/versions/node/v5.4.1/lib/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/joao/.nvm/versions/node/v5.4.1/lib/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/joao/.nvm/versions/node/v5.4.1/lib/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
```

**Comment by ryancrawcour** [comment]
Updated the readme.md for tests. 

https://github.com/Azure/azure-documentdb-node/blob/master/source/test/readme.md
